// Package gga implements the Guardian Angel pre-commit code review hook.
// It auto-detects the AI provider from selected agents, writes a global
// config to ~/.config/gga/config, and installs an AGENTS.md review template.
package gga

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/lleontor705/cortex-ia/internal/assets"
	"github.com/lleontor705/cortex-ia/internal/components/filemerge"
	"github.com/lleontor705/cortex-ia/internal/model"
)

// InjectionResult describes all files written by the GGA injection.
type InjectionResult struct {
	Files   []string
	Changed bool
}

// ModelConfig is the only input that permits a concrete model in GGA output.
// A model is executable only when it carries trusted configuration provenance.
type ModelConfig struct {
	Provider   string
	Model      string
	Provenance string
	Route      string
	Resolved   bool
	Deferred   bool
}

// SupportedProviders is the set of providers the GGA switcher accepts.
// `claude`, `opencode`, `gemini`, `codex` are agent-routed (auto-detected).
// `anthropic`, `openai`, `google`, `ollama` are direct-LLM providers used by
// the explicit `cortex-ia gga --provider` switcher.
var SupportedProviders = []string{
	"claude", "opencode", "gemini", "codex",
	"anthropic", "openai", "google", "ollama",
}

// IsValidProvider reports whether p is one of SupportedProviders.
func IsValidProvider(p string) bool {
	for _, valid := range SupportedProviders {
		if valid == p {
			return true
		}
	}
	return false
}

// ProviderForAgents identifies an explicitly selected agent provider. It never
// selects a model and returns an empty string when no provider is selected.
func ProviderForAgents(agentIDs []model.AgentID) string {
	set := make(map[model.AgentID]bool, len(agentIDs))
	for _, id := range agentIDs {
		set[id] = true
	}

	switch {
	case set[model.AgentClaudeCode]:
		return "claude"
	case set[model.AgentOpenCode]:
		return "opencode"
	case set[model.AgentGeminiCLI]:
		return "gemini"
	case set[model.AgentCodex]:
		return "codex"
	default:
		return ""
	}
}

// BuildConfig generates the GGA global config content.
// The output is a shell-sourceable file with key=value pairs.
//
// BuildConfig emits provider-only, unresolved configuration. It intentionally
// contains no model, endpoint, or static provider fallback.
func BuildConfig(provider string) []byte {
	content, _ := BuildConfigResolved(ModelConfig{Provider: provider, Deferred: provider != ""})
	return content
}

// BuildConfigResolved emits a configuration-backed model or an explicit
// route-only deferred/unresolved configuration.
func BuildConfigResolved(selection ModelConfig) ([]byte, error) {
	if selection.Provider != "" && !IsValidProvider(selection.Provider) {
		return nil, fmt.Errorf("gga: unsupported provider %q", selection.Provider)
	}
	if selection.Resolved {
		if selection.Provider == "" || selection.Model == "" || !trustedProvenance(selection.Provenance) {
			return nil, fmt.Errorf("gga: concrete model requires trusted configuration provenance")
		}
	} else if !selection.Deferred && selection.Route == "" {
		return nil, fmt.Errorf("gga: unresolved selection must defer or provide a route")
	}
	if selection.Route != "" && !strings.HasPrefix(selection.Route, "route/v") {
		return nil, fmt.Errorf("gga: invalid route %q", selection.Route)
	}
	var sb strings.Builder
	sb.WriteString("# GGA — Guardian Angel configuration\n")
	sb.WriteString("# Auto-generated by cortex-ia. Edit freely.\n\n")
	fmt.Fprintf(&sb, "PROVIDER=%q\n", selection.Provider)
	if selection.Resolved {
		fmt.Fprintf(&sb, "MODEL=%q\nMODEL_SOURCE=%q\nRESOLUTION=\"resolved\"\n", selection.Model, selection.Provenance)
	} else if selection.Route != "" {
		fmt.Fprintf(&sb, "ROUTE=%q\nRESOLUTION=\"deferred\"\n", selection.Route)
	} else {
		sb.WriteString("RESOLUTION=\"unresolved\"\n")
	}

	sb.WriteString("FILE_PATTERNS=\"*.go *.ts *.tsx *.js *.jsx *.py *.rs *.java *.rb\"\n")
	sb.WriteString("EXCLUDE_PATTERNS=\"vendor/* node_modules/* .git/* dist/* build/*\"\n")
	sb.WriteString("MAX_FILES=20\n")
	sb.WriteString("TIMEOUT=120\n")
	return []byte(sb.String()), nil
}

func trustedProvenance(source string) bool {
	return source == "user-config" || source == "provider-config"
}

// SetProvider rewrites ~/.config/gga/config to use the given provider.
// Returns true when the file changed; returns an error for invalid providers.
func SetProvider(homeDir, provider string) (bool, error) {
	if !IsValidProvider(provider) {
		return false, fmt.Errorf("gga: unsupported provider %q (valid: %v)", provider, SupportedProviders)
	}
	wr, err := filemerge.WriteFileAtomic(ConfigPath(homeDir), BuildConfig(provider), 0o644)
	if err != nil {
		return false, fmt.Errorf("gga: write config: %w", err)
	}
	return wr.Changed, nil
}

// ConfigPath returns the path to ~/.config/gga/config.
func ConfigPath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "gga", "config")
}

// AgentsTemplatePath returns the path to ~/.config/gga/AGENTS.md.
func AgentsTemplatePath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "gga", "AGENTS.md")
}

// Inject writes GGA config + AGENTS.md template to ~/.config/gga/.
func Inject(homeDir string, agentIDs []model.AgentID) (InjectionResult, error) {
	provider := ProviderForAgents(agentIDs)
	result := InjectionResult{}

	// Write config file.
	configContent := BuildConfig(provider)
	configPath := ConfigPath(homeDir)
	wr, err := filemerge.WriteFileAtomic(configPath, configContent, 0o644)
	if err != nil {
		return result, fmt.Errorf("gga: write config: %w", err)
	}
	result.Files = append(result.Files, configPath)
	result.Changed = result.Changed || wr.Changed

	// Write AGENTS.md template from embedded assets.
	agentsContent, err := assets.ReadBytes("gga/AGENTS.md")
	if err != nil {
		return result, fmt.Errorf("gga: read embedded AGENTS.md: %w", err)
	}
	agentsPath := AgentsTemplatePath(homeDir)
	wr, err = filemerge.WriteFileAtomic(agentsPath, agentsContent, 0o644)
	if err != nil {
		return result, fmt.Errorf("gga: write AGENTS.md: %w", err)
	}
	result.Files = append(result.Files, agentsPath)
	result.Changed = result.Changed || wr.Changed

	return result, nil
}
