// Package gga implements the Guardian Angel pre-commit code review hook.
// It auto-detects the AI provider from selected agents, writes a global
// config to ~/.config/gga/config, and installs an AGENTS.md review template.
package gga

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/lleontor705/cortex-ia/internal/assets"
	"github.com/lleontor705/cortex-ia/internal/components/filemerge"
	"github.com/lleontor705/cortex-ia/internal/model"
)

// InjectionResult describes all files written by the GGA injection.
type InjectionResult struct {
	Files   []string
	Changed bool
}

// SupportedProviders is the set of providers the GGA switcher accepts.
// `claude`, `opencode`, `gemini`, `codex` are agent-routed (auto-detected).
// `anthropic`, `openai`, `google`, `ollama` are direct-LLM providers used by
// the explicit `cortex-ia gga --provider` switcher.
var SupportedProviders = []string{
	"claude", "opencode", "gemini", "codex",
	"anthropic", "openai", "google", "ollama",
}

// IsValidProvider reports whether p is one of SupportedProviders.
func IsValidProvider(p string) bool {
	for _, valid := range SupportedProviders {
		if valid == p {
			return true
		}
	}
	return false
}

// ProviderForAgents auto-detects the GGA provider from selected agents.
// Priority: claude > opencode > gemini > codex > claude (default).
func ProviderForAgents(agentIDs []model.AgentID) string {
	set := make(map[model.AgentID]bool, len(agentIDs))
	for _, id := range agentIDs {
		set[id] = true
	}

	switch {
	case set[model.AgentClaudeCode]:
		return "claude"
	case set[model.AgentOpenCode]:
		return "opencode"
	case set[model.AgentGeminiCLI]:
		return "gemini"
	case set[model.AgentCodex]:
		return "codex"
	default:
		return "claude"
	}
}

// BuildConfig generates the GGA global config content.
// The output is a shell-sourceable file with key=value pairs.
//
// Direct-LLM providers (anthropic, openai, google, ollama) emit MODEL and
// — for ollama — API_BASE so the user can point at a non-default endpoint.
func BuildConfig(provider string) []byte {
	var sb strings.Builder
	sb.WriteString("# GGA — Guardian Angel configuration\n")
	sb.WriteString("# Auto-generated by cortex-ia. Edit freely.\n\n")
	fmt.Fprintf(&sb, "PROVIDER=%q\n", provider)

	switch provider {
	case "anthropic":
		sb.WriteString("MODEL=\"claude-sonnet-4-6\"\n")
	case "openai":
		sb.WriteString("MODEL=\"gpt-4o\"\n")
	case "google":
		sb.WriteString("MODEL=\"gemini-2.0-flash\"\n")
	case "ollama":
		sb.WriteString("MODEL=\"llama3.2\"\n")
		sb.WriteString("API_BASE=\"http://localhost:11434\"\n")
	}

	sb.WriteString("FILE_PATTERNS=\"*.go *.ts *.tsx *.js *.jsx *.py *.rs *.java *.rb\"\n")
	sb.WriteString("EXCLUDE_PATTERNS=\"vendor/* node_modules/* .git/* dist/* build/*\"\n")
	sb.WriteString("MAX_FILES=20\n")
	sb.WriteString("TIMEOUT=120\n")
	return []byte(sb.String())
}

// SetProvider rewrites ~/.config/gga/config to use the given provider.
// Returns true when the file changed; returns an error for invalid providers.
func SetProvider(homeDir, provider string) (bool, error) {
	if !IsValidProvider(provider) {
		return false, fmt.Errorf("gga: unsupported provider %q (valid: %v)", provider, SupportedProviders)
	}
	wr, err := filemerge.WriteFileAtomic(ConfigPath(homeDir), BuildConfig(provider), 0o644)
	if err != nil {
		return false, fmt.Errorf("gga: write config: %w", err)
	}
	return wr.Changed, nil
}

// ConfigPath returns the path to ~/.config/gga/config.
func ConfigPath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "gga", "config")
}

// AgentsTemplatePath returns the path to ~/.config/gga/AGENTS.md.
func AgentsTemplatePath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "gga", "AGENTS.md")
}

// Inject writes GGA config + AGENTS.md template to ~/.config/gga/.
func Inject(homeDir string, agentIDs []model.AgentID) (InjectionResult, error) {
	provider := ProviderForAgents(agentIDs)
	result := InjectionResult{}

	// Write config file.
	configContent := BuildConfig(provider)
	configPath := ConfigPath(homeDir)
	wr, err := filemerge.WriteFileAtomic(configPath, configContent, 0o644)
	if err != nil {
		return result, fmt.Errorf("gga: write config: %w", err)
	}
	result.Files = append(result.Files, configPath)
	result.Changed = result.Changed || wr.Changed

	// Write AGENTS.md template from embedded assets.
	agentsContent, err := assets.ReadBytes("gga/AGENTS.md")
	if err != nil {
		return result, fmt.Errorf("gga: read embedded AGENTS.md: %w", err)
	}
	agentsPath := AgentsTemplatePath(homeDir)
	wr, err = filemerge.WriteFileAtomic(agentsPath, agentsContent, 0o644)
	if err != nil {
		return result, fmt.Errorf("gga: write AGENTS.md: %w", err)
	}
	result.Files = append(result.Files, agentsPath)
	result.Changed = result.Changed || wr.Changed

	return result, nil
}
