package herdr

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

const defaultConfigToml = `# Herdr Configuration generated by cortex-ia
[ui]
sidebar_position = "left"
show_agent_status = true

[terminal]
scrollback_lines = 10000

[theme]
name = "default-dark"

[keys]
prefix = "ctrl+b"
`

// Install installs Herdr on the host system if not already installed.
func Install() error {
	fmt.Println("📦 Verificando/Instalando Herdr...")

	if _, err := exec.LookPath("herdr"); err == nil {
		fmt.Println("✅ Herdr ya está instalado en el sistema.")
		return nil
	}

	var cmd *exec.Cmd
	if runtime.GOOS == "windows" {
		fmt.Println("⬇️ Descargando e instalando Herdr para Windows (PowerShell)...")
		psScript := `powershell -ExecutionPolicy Bypass -c "irm https://herdr.dev/install.ps1 | iex"`
		cmd = exec.Command("cmd", "/C", psScript)
	} else {
		fmt.Println("⬇️ Descargando e instalando Herdr para Unix/macOS...")
		cmd = exec.Command("sh", "-c", "curl -fsSL https://herdr.dev/install.sh | sh")
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("falló la instalación de Herdr: %w", err)
	}

	fmt.Println("✅ Herdr instalado exitosamente.")
	return nil
}

// Setup configures Herdr config.toml, agent integrations, and status check.
func Setup() error {
	if err := Install(); err != nil {
		return err
	}

	fmt.Println("\n⚙️ Configurando el entorno de Herdr para Cortex-IA...")

	configDir, err := GetHerdrConfigDir()
	if err != nil {
		return err
	}

	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("no se pudo crear la carpeta de configuración de Herdr: %w", err)
	}

	configPath := filepath.Join(configDir, "config.toml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		if err := os.WriteFile(configPath, []byte(defaultConfigToml), 0644); err != nil {
			return fmt.Errorf("error al escribir config.toml: %w", err)
		}
		fmt.Printf("✅ Archivo de configuración creado en: %s\n", configPath)
	} else {
		fmt.Printf("ℹ️ Archivo de configuración existente conservado: %s\n", configPath)
	}

	if _, err := exec.LookPath("claude"); err == nil {
		fmt.Println("🔗 Instalando integración nativa de Claude Code en Herdr...")
		out, err := exec.Command("herdr", "integration", "install", "claude").CombinedOutput()
		if err != nil {
			fmt.Printf("⚠️ Advertencia al instalar integración de claude: %s\n", string(out))
		} else {
			fmt.Println("✅ Integración de Claude Code activada en Herdr.")
		}
	} else {
		fmt.Println("ℹ️ Claude Code no detectado en PATH.")
	}

	if _, err := exec.LookPath("agy"); err == nil {
		fmt.Println("✅ Antigravity CLI ('agy') detectado y listo para delegación en Herdr.")
	} else {
		fmt.Println("ℹ️ Antigravity CLI ('agy') no detectado en PATH.")
	}

	fmt.Println("\n🎉 ¡Entorno Herdr + Cortex-IA listo!")
	fmt.Println("👉 Para usarlo con delegación: ejecuta 'herdr' y dentro abre tu orquestador.")
	fmt.Println("👉 Si ejecutas OpenCode fuera de Herdr: funcionará automáticamente en modo nativo.")
	return nil
}

// Status checks and prints diagnostics for Herdr, agy, and claude.
func Status() error {
	fmt.Println("🔍 Diagnóstico del Entorno Herdr + Cortex-IA:")

	herdrPath, err := exec.LookPath("herdr")
	if err != nil {
		fmt.Println("❌ Herdr: NO instalado (ejecuta 'cortex-ia herdr install')")
	} else {
		fmt.Printf("✅ Herdr: Instalado en %s\n", herdrPath)
	}

	agyPath, err := exec.LookPath("agy")
	if err != nil {
		fmt.Println("⚠️ Antigravity CLI (agy): NO encontrado en PATH")
	} else {
		fmt.Printf("✅ Antigravity CLI: %s\n", agyPath)
	}

	claudePath, err := exec.LookPath("claude")
	if err != nil {
		fmt.Println("⚠️ Claude Code: NO encontrado en PATH")
	} else {
		fmt.Printf("✅ Claude Code: %s\n", claudePath)
	}

	if os.Getenv("HERDR_ENV") == "1" {
		fmt.Printf("🟢 Sesión actual: CORRIENDO DENTRO DE HERDR (Workspace: %s, Pane: %s)\n",
			os.Getenv("HERDR_WORKSPACE_ID"), os.Getenv("HERDR_PANE_ID"))
	} else {
		fmt.Println("⚪ Sesión actual: Terminal Estándar (Modo nativo OpenCode)")
	}

	return nil
}

// GetHerdrConfigDir resolves the operating system configuration directory for Herdr.
func GetHerdrConfigDir() (string, error) {
	if runtime.GOOS == "windows" {
		appData := os.Getenv("APPDATA")
		if appData == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return "", err
			}
			appData = filepath.Join(home, "AppData", "Roaming")
		}
		return filepath.Join(appData, "herdr"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "herdr"), nil
}
