package herdr

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const defaultConfigToml = `# Herdr Configuration generated by cortex-ia
[ui]
sidebar_position = "left"
show_agent_status = true

[terminal]
scrollback_lines = 10000

[theme]
name = "default-dark"

[keys]
prefix = "ctrl+b"
`

// Install installs Herdr on the host system if not already installed.
func Install() error {
	fmt.Println("📦 Verificando/Instalando Herdr...")

	if _, err := ResolveHerdr(); err == nil {
		fmt.Println("✅ Herdr ya está instalado en el sistema.")
		return nil
	}

	var cmd *exec.Cmd
	if runtime.GOOS == "windows" {
		fmt.Println("⬇️ Descargando e instalando Herdr para Windows (PowerShell)...")
		psScript := `powershell -ExecutionPolicy Bypass -c "irm https://herdr.dev/install.ps1 | iex"`
		cmd = exec.Command("cmd", "/C", psScript)
	} else {
		fmt.Println("⬇️ Descargando e instalando Herdr para Unix/macOS...")
		cmd = exec.Command("sh", "-c", "curl -fsSL https://herdr.dev/install.sh | sh")
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("falló la instalación de Herdr: %w", err)
	}

	fmt.Println("✅ Herdr instalado exitosamente.")
	return nil
}

// Setup configures Herdr config.toml, agent integrations, and status check.
func Setup() error {
	if err := Install(); err != nil {
		return err
	}

	fmt.Println("\n⚙️ Configurando el entorno de Herdr para Cortex-IA...")

	configDir, err := GetHerdrConfigDir()
	if err != nil {
		return err
	}

	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("no se pudo crear la carpeta de configuración de Herdr: %w", err)
	}

	configPath := filepath.Join(configDir, "config.toml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		if err := os.WriteFile(configPath, []byte(defaultConfigToml), 0644); err != nil {
			return fmt.Errorf("error al escribir config.toml: %w", err)
		}
		fmt.Printf("✅ Archivo de configuración creado en: %s\n", configPath)
	} else {
		fmt.Printf("ℹ️ Archivo de configuración existente conservado: %s\n", configPath)
	}

	herdrPath, err := ResolveHerdr()
	if err != nil {
		return err
	}
	for _, integration := range []string{"opencode", "antigravity-cli"} {
		fmt.Printf("🔗 Instalando integración %s en Herdr...\n", integration)
		out, err := exec.Command(herdrPath, "integration", "install", integration).CombinedOutput()
		if err != nil {
			fmt.Printf("⚠️ Advertencia al instalar integración %s: %s\n", integration, string(out))
		} else {
			fmt.Printf("✅ Integración %s activada en Herdr.\n", integration)
		}
	}

	// Instalar plugin cortex-sync en Herdr
	pluginDir := filepath.Join(configDir, "plugins", "cortex-sync")
	if err := os.MkdirAll(pluginDir, 0755); err == nil {
		manifestPath := filepath.Join(pluginDir, "herdr-plugin.toml")
		pluginToml := `[plugin]
name = "cortex-sync"
version = "1.0.0"
description = "Syncs Herdr terminal pane lifecycle and agent states with cortex-ia SQLite Control Plane"
author = "usrLuisLeon & Antigravity"

[hooks]
on_agent_state_change = "cortex-ia delegate sync-herdr"
on_pane_close = "cortex-ia delegate recover"
`
		if err := os.WriteFile(manifestPath, []byte(pluginToml), 0644); err == nil {
			fmt.Printf("✅ Plugin Herdr 'cortex-sync' instalado en: %s\n", manifestPath)
		}
	}

	if _, err := ResolveAGY(); err == nil {
		fmt.Println("✅ Antigravity CLI ('agy') detectado y listo para delegación en Herdr.")
	} else {
		fmt.Println("ℹ️ Antigravity CLI ('agy') no detectado en PATH.")
	}

	fmt.Println("\n🎉 ¡Entorno Herdr + Cortex-IA listo!")
	fmt.Println("👉 Para usarlo con delegación: ejecuta 'herdr' y dentro abre tu orquestador.")
	fmt.Println("👉 Si ejecutas OpenCode fuera de Herdr: funcionará automáticamente en modo nativo.")
	return nil
}

// Status checks and prints diagnostics for the supervised bridge dependencies.
func Status() error {
	fmt.Println("🔍 Diagnóstico del Entorno Herdr + Cortex-IA:")

	herdrPath, err := ResolveHerdr()
	if err != nil {
		fmt.Println("❌ Herdr: NO instalado (ejecuta 'cortex-ia herdr install')")
	} else {
		fmt.Printf("✅ Herdr: Instalado en %s\n", herdrPath)
	}

	agyPath, err := ResolveAGY()
	if err != nil {
		fmt.Println("⚠️ Antigravity CLI (agy): NO encontrado en PATH")
	} else {
		fmt.Printf("✅ Antigravity CLI: %s\n", agyPath)
	}

	if HerdrRunning(herdrPath) {
		fmt.Println("🟢 Entorno Herdr: ACTIVO (Multiplexación y división de paneles en vivo habilitada)")
	} else {
		fmt.Println("⚪ Sesión actual: Terminal Estándar (Modo nativo OpenCode)")
	}

	return nil
}

// ResolveHerdr includes the canonical Windows installer location because the
// installer does not always update the parent process PATH immediately.
func ResolveHerdr() (string, error) {
	if found, err := exec.LookPath("herdr"); err == nil {
		return found, nil
	}
	home, _ := os.UserHomeDir()
	local := os.Getenv("LOCALAPPDATA")
	if local == "" && home != "" {
		local = filepath.Join(home, "AppData", "Local")
	}
	candidates := []string{
		filepath.Join(local, "Programs", "Herdr", "bin", "herdr.exe"),
		filepath.Join(home, ".cargo", "bin", "herdr.exe"),
		"/usr/local/bin/herdr", "/usr/bin/herdr",
	}
	return firstRegular(candidates, "herdr")
}

func ResolveAGY() (string, error) {
	if found, err := exec.LookPath("agy"); err == nil {
		return found, nil
	}
	home, _ := os.UserHomeDir()
	local := os.Getenv("LOCALAPPDATA")
	if local == "" && home != "" {
		local = filepath.Join(home, "AppData", "Local")
	}
	return firstRegular([]string{
		filepath.Join(local, "agy", "bin", "agy.exe"),
		filepath.Join(home, ".agy", "bin", "agy"),
		"/usr/local/bin/agy", "/usr/bin/agy",
	}, "agy")
}

func firstRegular(candidates []string, name string) (string, error) {
	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("%s executable not found", name)
}

func HerdrRunning(herdrPath string) bool {
	if os.Getenv("HERDR_ENV") == "1" || os.Getenv("HERDR_WORKSPACE_ID") != "" {
		return true
	}
	if herdrPath == "" {
		return false
	}
	cmd := exec.Command(herdrPath, "pane", "list")
	out, err := cmd.Output()
	if err == nil && (strings.Contains(string(out), "pane_list") || strings.Contains(string(out), "panes")) {
		return true
	}
	return false
}

// GetHerdrConfigDir resolves the operating system configuration directory for Herdr.
func GetHerdrConfigDir() (string, error) {
	if runtime.GOOS == "windows" {
		appData := os.Getenv("APPDATA")
		if appData == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return "", err
			}
			appData = filepath.Join(home, "AppData", "Roaming")
		}
		return filepath.Join(appData, "herdr"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "herdr"), nil
}
