package cutover

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/lleontor705/cortex-ia/internal/assets/roles"
	phaseassets "github.com/lleontor705/cortex-ia/internal/assets/schemas/generator"
	"github.com/lleontor705/cortex-ia/internal/components/sdd/install"
	"github.com/lleontor705/cortex-ia/internal/components/sdd/ir"
	"github.com/lleontor705/cortex-ia/internal/components/sdd/renderers"
)

func TestMajorBoundaryCutoverRequiresDryRunThenAppliesOwnedBundleAndRollsBack(t *testing.T) {
	root := t.TempDir()
	backupRoot := filepath.Join(t.TempDir(), "backups")
	legacyPath := "skills/apply/SKILL.md"
	legacy := []byte("legacy managed apply skill\n")
	writeFile(t, root, legacyPath, legacy)
	writeFile(t, root, "runtime-state/session.json", []byte("active-runtime-state\n"))

	priorOwnership, err := install.NewOwnership(legacyPath, "1.9.0", "asset/skill/apply", legacy, legacy)
	if err != nil {
		t.Fatal(err)
	}
	checks := make([]string, 0, 3)
	request := Request{
		Root:             root,
		BackupRoot:       backupRoot,
		Workflow:         canonicalWorkflow(),
		Options:          phaseassets.Options{Profile: roles.ProfilePortableSequential},
		GeneratorVersion: "2.0.0",
		Managed: []install.ManagedAsset{{
			Path: legacyPath, Ownership: priorOwnership, Base: legacy, Mode: 0o600,
		}},
		ActiveSession: true,
		PreDoctor: func() error {
			checks = append(checks, "pre-doctor")
			return nil
		},
		StaticConformance: func(renderers.Bundle) error {
			checks = append(checks, "static-conformance")
			return nil
		},
		PostDoctor: func(renderers.Bundle) error {
			checks = append(checks, "post-doctor")
			return nil
		},
	}

	before := treeHashes(t, root)
	prepared, err := Prepare(request)
	if err != nil {
		t.Fatalf("Prepare() error = %v", err)
	}
	if after := treeHashes(t, root); !reflect.DeepEqual(after, before) {
		t.Fatalf("dry-run mutated target tree: before=%v after=%v", before, after)
	}
	if !prepared.Plan.Backup.Required || len(prepared.Plan.Updates) != 1 || len(prepared.Plan.Creates) == 0 {
		t.Fatalf("dry-run plan = %#v", prepared.Plan)
	}
	if !strings.Contains(prepared.Warning, "reload") || !strings.Contains(prepared.Warning, "active session") {
		t.Fatalf("active-session warning = %q", prepared.Warning)
	}
	if !reflect.DeepEqual(checks, []string{"pre-doctor", "static-conformance"}) {
		t.Fatalf("pre-apply checks = %v", checks)
	}

	result, err := Apply(prepared)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if !result.Receipt.BackupVerified || !result.Receipt.RestoreAvailable {
		t.Fatalf("apply receipt = %#v", result.Receipt)
	}
	if !reflect.DeepEqual(checks, []string{"pre-doctor", "static-conformance", "post-doctor"}) {
		t.Fatalf("cutover checks = %v", checks)
	}
	if got := readFile(t, root, "runtime-state/session.json"); !bytes.Equal(got, []byte("active-runtime-state\n")) {
		t.Fatalf("runtime state migrated or mutated: %q", got)
	}

	for _, asset := range result.Bundle.Assets {
		content := readFile(t, root, asset.Path)
		if !bytes.Equal(content, asset.Content) {
			t.Errorf("installed asset %q differs from generated bytes", asset.Path)
		}
		metadata, base, readErr := install.NewOwnershipStore(root).Read(asset.Path)
		if readErr != nil {
			t.Errorf("read ownership for %q: %v", asset.Path, readErr)
			continue
		}
		if metadata.GeneratorVersion != "2.0.0" || metadata.SemanticID != asset.SemanticID || !bytes.Equal(base, asset.Content) {
			t.Errorf("ownership for %q = %#v base=%q", asset.Path, metadata, base)
		}
	}
	manifest := readFile(t, root, ManifestPath)
	if !bytes.Contains(manifest, []byte(`"generator_version": "2.0.0"`)) || !bytes.Contains(manifest, []byte(`"bundle_sha256"`)) {
		t.Fatalf("generated manifest is incomplete:\n%s", manifest)
	}

	again, err := Prepare(request)
	if err != nil {
		t.Fatalf("second Prepare() error = %v", err)
	}
	if !reflect.DeepEqual(result.Bundle, again.Bundle) {
		t.Fatal("owned bundle and manifest are not deterministic")
	}

	rollback, err := install.Rollback(result.Receipt, func() error { return nil })
	if err != nil || !rollback.DoctorPassed {
		t.Fatalf("Rollback() = %#v, %v", rollback, err)
	}
	if got := readFile(t, root, legacyPath); !bytes.Equal(got, legacy) {
		t.Fatalf("rollback legacy bytes = %q, want %q", got, legacy)
	}
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(legacyPath+".cortex-ia.json"))); !os.IsNotExist(err) {
		t.Fatalf("rollback retained migrated ownership sidecar: %v", err)
	}
}

func TestMajorBoundaryCutoverBlocksCustomizedManagedAssetWithoutOverwrite(t *testing.T) {
	root := t.TempDir()
	path := "skills/apply/SKILL.md"
	base := []byte("legacy managed apply skill\n")
	customized := []byte("user customized apply skill\n")
	writeFile(t, root, path, customized)
	ownership, err := install.NewOwnership(path, "1.9.0", "asset/skill/apply", base, base)
	if err != nil {
		t.Fatal(err)
	}

	prepared, err := Prepare(Request{
		Root: root, BackupRoot: filepath.Join(t.TempDir(), "backups"), Workflow: canonicalWorkflow(),
		Options: phaseassets.Options{Profile: roles.ProfilePortableSequential}, GeneratorVersion: "2.0.0",
		Managed:   []install.ManagedAsset{{Path: path, Ownership: ownership, Base: base, Mode: 0o600}},
		PreDoctor: func() error { return nil }, StaticConformance: func(renderers.Bundle) error { return nil }, PostDoctor: func(renderers.Bundle) error { return nil },
	})
	if err != nil {
		t.Fatalf("Prepare() error = %v", err)
	}
	if len(prepared.Plan.Conflicts) != 1 || prepared.Plan.Conflicts[0].State != install.OwnershipCustomized {
		t.Fatalf("customization conflicts = %#v", prepared.Plan.Conflicts)
	}
	if _, err := Apply(prepared); err == nil || !strings.Contains(err.Error(), "conflict") {
		t.Fatalf("Apply() error = %v, want blocking conflict", err)
	}
	if got := readFile(t, root, path); !bytes.Equal(got, customized) {
		t.Fatalf("conflicting customization was overwritten: %q", got)
	}
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(ManifestPath))); !os.IsNotExist(err) {
		t.Fatalf("conflicting cutover wrote manifest: %v", err)
	}
}

func TestMajorBoundaryCutoverPreservesNonConflictingCustomizationByThreeWayMerge(t *testing.T) {
	root := t.TempDir()
	workflow := canonicalWorkflow()
	generated, err := phaseassets.Generate(workflow, phaseassets.Options{Profile: roles.ProfilePortableSequential})
	if err != nil {
		t.Fatal(err)
	}
	var desired []byte
	for _, asset := range generated {
		if asset.Path == "skills/apply/SKILL.md" {
			desired = asset.Content
			break
		}
	}
	if len(desired) == 0 {
		t.Fatal("apply skill was not generated")
	}
	base := bytes.ReplaceAll(desired, []byte("2.0.0"), []byte("1.9.0"))
	current := append(append([]byte(nil), base...), []byte("\nUser customization: keep this note.\n")...)
	path := "skills/apply/SKILL.md"
	writeFile(t, root, path, current)
	ownership, err := install.NewOwnership(path, "1.9.0", "asset/skill/apply", base, base)
	if err != nil {
		t.Fatal(err)
	}

	prepared, err := Prepare(Request{
		Root: root, BackupRoot: filepath.Join(t.TempDir(), "backups"), Workflow: workflow,
		Options: phaseassets.Options{Profile: roles.ProfilePortableSequential}, GeneratorVersion: "2.0.0",
		Managed:   []install.ManagedAsset{{Path: path, Ownership: ownership, Base: base, Mode: 0o600}},
		PreDoctor: func() error { return nil }, StaticConformance: func(renderers.Bundle) error { return nil }, PostDoctor: func(renderers.Bundle) error { return nil },
	})
	if err != nil {
		t.Fatalf("Prepare() error = %v", err)
	}
	if len(prepared.Plan.Conflicts) != 0 || len(prepared.Plan.Updates) != 1 {
		t.Fatalf("non-conflicting customization plan = %#v", prepared.Plan)
	}
	if !bytes.Contains(prepared.Plan.Updates[0].Content, []byte("User customization: keep this note.")) || !bytes.Contains(prepared.Plan.Updates[0].Content, []byte("2.0.0")) {
		t.Fatalf("three-way merged content =\n%s", prepared.Plan.Updates[0].Content)
	}
	result, err := Apply(prepared)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	installed := readFile(t, root, path)
	if !bytes.Contains(installed, []byte("User customization: keep this note.")) || !bytes.Contains(installed, []byte("2.0.0")) {
		t.Fatalf("installed customization merge =\n%s", installed)
	}
	metadata, recordedBase, err := install.NewOwnershipStore(root).Read(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(recordedBase, desired) || metadata.ContentSHA256 != install.SHA256(installed) {
		t.Fatalf("merged ownership metadata = %#v base-match=%t", metadata, bytes.Equal(recordedBase, desired))
	}
	if _, err := install.Rollback(result.Receipt, func() error { return nil }); err != nil {
		t.Fatalf("Rollback() error = %v", err)
	}
	if got := readFile(t, root, path); !bytes.Equal(got, current) {
		t.Fatalf("rollback did not restore prior customized bundle:\n%s", got)
	}
}

func canonicalWorkflow() ir.WorkflowIR {
	version := ir.MustParseVersion("2.0.0")
	return ir.WorkflowIR{
		SchemaVersion: version, ID: "workflow/sdd", Version: version,
		Roles: []ir.Role{
			{ID: "role/implement", Objective: "Implement one bounded vertical work unit.", Outputs: []ir.Contract{{ID: "contract/apply", SchemaVersion: version, Required: true}}, TerminalStates: []ir.TerminalState{ir.TerminalSuccess, ir.TerminalBlocked}},
			{ID: "role/validate", Objective: "Independently validate outcomes and evidence.", Inputs: []ir.Contract{{ID: "contract/apply", SchemaVersion: version, Required: true}}, Outputs: []ir.Contract{{ID: "contract/verify", SchemaVersion: version, Required: true}}, TerminalStates: []ir.TerminalState{ir.TerminalSuccess, ir.TerminalBlocked}},
		},
		Phases: []ir.Phase{{ID: "phase/apply", Role: "role/implement"}, {ID: "phase/verify", Role: "role/validate", DependsOn: []ir.SemanticID{"phase/apply"}}},
	}
}

func writeFile(t *testing.T, root, path string, content []byte) {
	t.Helper()
	fullPath := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fullPath, content, 0o600); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, root, path string) []byte {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		t.Fatal(err)
	}
	return content
}

func treeHashes(t *testing.T, root string) map[string]string {
	t.Helper()
	result := map[string]string{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		result[filepath.ToSlash(relative)] = install.SHA256(content)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}
